"""empty message

Revision ID: 624e6fe055c5
Revises: ff2a66f06138
Create Date: 2023-05-06 11:08:30.146968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624e6fe055c5'
down_revision = 'ff2a66f06138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('reservation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_number', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.DateTime(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('number_of_nights', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.hotel_id'], ),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    # ### end Alembic commands ###
