"""empty message

Revision ID: 2a23ed17004b
Revises: 29c1ee2bf7b4
Create Date: 2023-05-06 11:00:56.641922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a23ed17004b'
down_revision = '29c1ee2bf7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('room_type_name', sa.String(length=280), nullable=False),
    sa.Column('room_default_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.hotel_id'], ),
    sa.PrimaryKeyConstraint('hotel_id', 'room_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms')
    # ### end Alembic commands ###
