"""empty message

Revision ID: ff2a66f06138
Revises: fa7b5237735c
Create Date: 2023-05-06 11:07:07.701787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2a66f06138'
down_revision = 'fa7b5237735c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=280), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.hotel_id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('review_likes',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.review_id'], ),
    sa.PrimaryKeyConstraint('member_id', 'review_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_likes')
    op.drop_table('reviews')
    # ### end Alembic commands ###
