"""empty message

Revision ID: 01340b70acd3
Revises: 624e6fe055c5
Create Date: 2023-05-09 08:12:50.233669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01340b70acd3'
down_revision = '624e6fe055c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('username', sa.String(length=128), nullable=True))
    op.add_column('members', sa.Column('password', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'members', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'members', type_='unique')
    op.drop_column('members', 'password')
    op.drop_column('members', 'username')
    # ### end Alembic commands ###
