"""empty message

Revision ID: 29c1ee2bf7b4
Revises: 
Create Date: 2023-05-06 10:57:51.919407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c1ee2bf7b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('hotel_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('star_rating', sa.Float(), nullable=True),
    sa.Column('number_of_rooms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('hotel_id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotels')
    # ### end Alembic commands ###
